// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBoeNYAFQOuQ3FUqXgTTDjVhmRKP0TBn2A',
    appId: '1:548448981597:web:ef85e664fb4b500fabb3b4',
    messagingSenderId: '548448981597',
    projectId: 'warehouse-app-d3b44',
    authDomain: 'warehouse-app-d3b44.firebaseapp.com',
    databaseURL: 'https://warehouse-app-d3b44-default-rtdb.firebaseio.com',
    storageBucket: 'warehouse-app-d3b44.appspot.com',
    measurementId: 'G-Z9D5V6FYLB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCclZ5SIyREOaRWDpsFs60hzkme5qzUC3E',
    appId: '1:548448981597:android:03fd6a6ab84d6e87abb3b4',
    messagingSenderId: '548448981597',
    projectId: 'warehouse-app-d3b44',
    databaseURL: 'https://warehouse-app-d3b44-default-rtdb.firebaseio.com',
    storageBucket: 'warehouse-app-d3b44.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdnrkf-pFBnbfr-7-yLM17J_AXHGZbMls',
    appId: '1:548448981597:ios:3e5c779d30f4045eabb3b4',
    messagingSenderId: '548448981597',
    projectId: 'warehouse-app-d3b44',
    databaseURL: 'https://warehouse-app-d3b44-default-rtdb.firebaseio.com',
    storageBucket: 'warehouse-app-d3b44.appspot.com',
    iosBundleId: 'com.example.newProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAdnrkf-pFBnbfr-7-yLM17J_AXHGZbMls',
    appId: '1:548448981597:ios:3e5c779d30f4045eabb3b4',
    messagingSenderId: '548448981597',
    projectId: 'warehouse-app-d3b44',
    databaseURL: 'https://warehouse-app-d3b44-default-rtdb.firebaseio.com',
    storageBucket: 'warehouse-app-d3b44.appspot.com',
    iosBundleId: 'com.example.newProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBoeNYAFQOuQ3FUqXgTTDjVhmRKP0TBn2A',
    appId: '1:548448981597:web:3817ff087ce0e465abb3b4',
    messagingSenderId: '548448981597',
    projectId: 'warehouse-app-d3b44',
    authDomain: 'warehouse-app-d3b44.firebaseapp.com',
    databaseURL: 'https://warehouse-app-d3b44-default-rtdb.firebaseio.com',
    storageBucket: 'warehouse-app-d3b44.appspot.com',
    measurementId: 'G-0RD2ZV9V8S',
  );
}
